// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlahlnvscrhiathjnpvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsYWhsbnZzY3JoaWF0aGpucHZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDY5NjMsImV4cCI6MjA2NjE4Mjk2M30.uthvuJa8DLQmP62cF0gPoAiwNTLtBpKmeKA4AcOgKr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);